environment:
  matrix:
    - nodejs_version: '13'

install:
  - npm install

before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=5346
  - PATH=C:\Program Files\PostgreSQL\12\bin\;%PATH%
  - createdb testdb

services:
  - postgresql101

test_script:
  - npm test

build: off
